namespace Falcon.FSATS.ResourceManagement.Application;

public sealed record ApplicationResourceProfile(
    string MinimumSafe,
    string Desired,
    string CeilingOrUsefulBound,
    string PressureSemantics,
    string Reclaimability,
    string DegradedOrSheddingSemantics,
    string RestorationSemantics);

public sealed record ApplicationManifest(
    string ApplicationId, string PackageId, string Version, string Owner, string Purpose,
    string PackageProvenance, string PackageIntegrityPolicy, string CompatibilityPolicy, string LifecycleState, string OwnedBusinessBoundary,
    string MsaId, IReadOnlyList<string> LsaIds, IReadOnlyList<string> CsaIds, string CsaEligibilityPolicy,
    IReadOnlyList<string> DeclaredDependencies, IReadOnlyList<string> RequiredFoundationCapabilities, IReadOnlyList<string> RequiredFoundationContracts,
    IReadOnlyList<string> ProvidedCapabilities, IReadOnlyList<string> DeclaredConsumers, IReadOnlyList<string> Permissions, IReadOnlyList<string> AuthorityRequests,
    string SecurityProfile, string ResourcePolicy, string PersistencePolicy, string CommunicationPolicy, string ConfigurationPolicy, string EvidencePolicy,
    string LifecyclePolicy, string HealthPolicy, string FailureContainmentPolicy, string SelfDevelopmentPolicy, string GuardianRequirement,
    string ProtectionInterface, string RollbackPlan, IReadOnlyList<string> ProhibitedResponsibilities,
    bool RuntimeAuthorized, bool FoundationResourceBindingBound)
{
    public ApplicationResourceProfile ResourceProfile { get; init; } = new("UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED");
    public string SafetyContinuityPolicy { get; init; } = "UNDECLARED";
    public string AiRepairRecoveryPolicy { get; init; } = "UNDECLARED";
    public string ReplacementRemovalPolicy { get; init; } = "UNDECLARED";
    public string ManifestGeneration { get; init; } = "PART3_BASE_MANIFEST_GENERATION";
    public string ManifestGenerationLifecycleState { get; init; } = "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE";
    public string CurrentGovernedApplicationState { get; init; } = "PART8_OWNER_ACCEPTED_AND_CLOSED_NOT_RUNTIME_ACTIVE";
    public bool CurrentGovernedStateGrantsRuntimeAuthority { get; init; } = false;
}

public static class ResourceManagementManifest
{
    public static ApplicationManifest Current { get; } = new(
        "APP-RSC", "Falcon.FSATS.ResourceManagement", "0.1.0-part3", "FSATS Application Workstream",
        "FSATS-only bounded resource coordination among independently admitted constituent Applications.",
        "APPLICATION_DEVELOPMENT_GOVERNED_SOURCE", "EXACT_BUILD_ARTIFACT_IDENTITY_AND_DIGEST_REQUIRED_BEFORE_ADMISSION",
        "CONTRACT_VERSION_AND_FOUNDATION_BINDING_MUST_BE_EXPLICITLY_VERIFIED", "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE",
        "FSATS_INTERNAL_RESOURCE_COORDINATION_WITHIN_FOUNDATION_ADMITTED_ENVELOPES_ONLY",
        "MSA-APP-RSC-01", Array.AsReadOnly(Enumerable.Range(1, 3).Select(i => $"R-LSA-{i:00}").ToArray()), Array.AsReadOnly(Array.Empty<string>()),
        "NO_INITIAL_CSA; FUTURE_CSA_REQUIRES_OWNER_ACCEPTED_ELIGIBILITY_AND_EXACT_PARENT_LSA",
        Array.AsReadOnly(new[] { "TRADING:GOVERNED_RESOURCE_CLAIMS", "FSAPMA:GOVERNED_RESOURCE_CLAIMS", "TRADING_GUARDIAN:GOVERNED_RESOURCE_CLAIMS", "FSTSIMA:GOVERNED_RESOURCE_CLAIMS" }),
        Array.AsReadOnly(new[] { "ApplicationLifecycle", "Communication", "Evidence", "Resources", "Security", "Persistence" }),
        Array.AsReadOnly(new[] { "APP-001", "CON-023", "FOUNDATION_RESOURCE_STATE", "FOUNDATION_LOAD_SHEDDING", "EVIDENCE", "LIFECYCLE", "PERSISTENCE" }),
        Array.AsReadOnly(new[] { "FSATS_RESOURCE_CLAIM_INTEGRITY", "BOUNDED_INTERNAL_COORDINATION", "RESIDUAL_RESOURCE_REQUEST_PREPARATION", "APPLICATION_DURABLE_RESTART_RECONSTRUCTION" }),
        Array.AsReadOnly(new[] { "FOUR_INDEPENDENT_FSATS_PEER_APPLICATIONS" }),
        Array.AsReadOnly(new[] { "APPLICATION_OWNED_COORDINATION_STATE", "GOVERNED_PERSISTENCE_PORT_ONLY", "NO_FOUNDATION_GRANT_CEILING_FLOOR_OR_TOTAL_RESOURCE_TRUTH_MINTING" }),
        Array.AsReadOnly(new[] { "NO_RUNTIME_AUTHORITY_ACTIVE", "NO_CANONICAL_FOUNDATION_BINDING_ACTIVE", "NO_PRODUCTION_PERSISTENCE_BINDING_AUTHORITY_ACTIVE" }),
        "DENY_UNDECLARED_RESOURCE_AUTHORITY; FOUNDATION_PROJECTION_IDENTITY_EPOCH_AND_DECISION_BINDING_REQUIRED",
        "INTERNAL_REDISTRIBUTION_FIRST; FOUNDATION_ADDITIONAL_REQUEST_SECOND; NEVER_EXCEED_FOUNDATION_GRANT_CEILING_OR_PROTECTION_FLOOR",
        "APPLICATION_OWNED_FSATS_COORDINATION_EPOCH_DECISION_AND_FENCING_STATE_HAVE_VERSIONED_DIGEST_BOUND_RECONSTRUCTION_SEMANTICS; PERSISTED_FOUNDATION_ENVELOPE_OR_EPOCH_IS_HISTORICAL_EVIDENCE_ONLY_AFTER_RESTART; FRESH_FOUNDATION_TRUTH_REQUIRED_BEFORE_NEW_REDISTRIBUTION; GOVERNED_FOUNDATION_PERSISTENCE_BINDING_REQUIRED_FOR_RUNTIME; NO_LOCAL_PRODUCTION_SUBSTITUTE",
        "DECLARED_RESOURCE_CLAIM_AND_FOUNDATION_BINDING_CONTRACTS_ONLY; REQUEST_IS_NOT_GRANT; STALE_EPOCH_FAILS_CLOSED",
        "GOVERNED_COORDINATION_POLICY_ONLY; NO_LOCAL_REINTERPRETATION_OF_FOUNDATION_RESOURCE_POLICY",
        "CLAIM_PROJECTION_EPOCH_REQUEST_DECISION_GRANT_REBALANCE_DURABILITY_AND_RECONSTRUCTION_EVIDENCE_MUST_REMAIN_ATTRIBUTABLE",
        "LIFECYCLE_STATES_DISTINCT; PART3_DOES_NOT_GRANT_FOUNDATION_RESOURCE_RUNTIME_BINDING; RESTART_DOES_NOT_REACTIVATE_OLD_COORDINATION_AUTHORITY",
        "REPORT_COORDINATION_EPOCH_CLAIM_INTEGRITY_PRESSURE_DEGRADED_RECONSTRUCTION_STATE_AND_MSA_LSA_HEALTH",
        "CONTAIN_INVALID_OR_STALE_CLAIMS_TO_THE_ORIGINATING_APPLICATION; UNKNOWN_RESOURCE_TRUTH_DENIES_RISK_INCREASING_REALLOCATION",
        "MSA_OR_LSA_ORIGIN_PROPOSALS_FOLLOW_ORIGIN_TO_MSA_TO_FSA_TO_SEPARATE_OWNER_GOVERNANCE; NO_INITIAL_CSA",
        "TRADING_GUARDIAN_PROTECTION_FLOORS_AND_FOUNDATION_RESTRICTIONS_CANNOT_BE_OVERRIDDEN_BY_APP_RSC",
        "RESOURCE_STATUS_AND_COORDINATION_INTERFACES_ONLY; NO_FOUNDATION_ENFORCEMENT_OWNERSHIP",
        "ROLLBACK_OR_APPROVED_CORRECTIVE_ACTION_MUST_RECONCILE_CLAIMS_EPOCHS_GRANTS_DURABLE_FENCES_EVIDENCE_AND_PEER_STATE",
        Array.AsReadOnly(new[] { "FoundationResourceGovernance", "FalconWideResourceAuthority", "FoundationPersistenceImplementation", "PeerBusinessOwnership", "FSATSContainerAuthority" }),
        RuntimeAuthorized: false, FoundationResourceBindingBound: false)
    {
        ResourceProfile = new(
            "MINIMUM_CAPACITY_TO_PRESERVE_CURRENT_FOUNDATION_ENVELOPE_PROTECTED_MINIMA_CLAIM_INTEGRITY_DURABLE_FENCES_AND_ATTRIBUTION",
            "NORMAL_FSATS_INTERNAL_COORDINATION_REBALANCE_AND_RESIDUAL_REQUEST_PREPARATION_CAPACITY_WITHIN_ADMITTED_ALLOCATION",
            "EXACT_CURRENT_FOUNDATION_GRANT_CEILING_OR_USEFUL_BOUND_ONLY_NEVER_APP_RSC_MINTED",
            "PRESSURE_MUST_OBEY_FOUNDATION_LOAD_SHEDDING_AND_PROTECTED_MINIMA_BEFORE_ANY_APP_RSC_OPTIMIZATION",
            "NONESSENTIAL_OPTIMIZATION_ANALYTICS_AND_OPTIONAL_REBALANCE_SEARCH_ARE_RECLAIMABLE",
            "FREEZE_UNTRUSTED_INTELLIGENT_REDISTRIBUTION; NEVER_EVICT_CURRENT_EPOCH_FENCING_OR_UNRESOLVED_COORDINATION_EVIDENCE",
            "RESTORE_ONLY_AFTER_FRESH_FOUNDATION_PROJECTION_NEWER_COORDINATION_EPOCH_GRANT_IDENTITY_LOAD_SHEDDING_AND_PEER_CLAIMS_ARE_REVALIDATED"),
        SafetyContinuityPolicy = "KILL_OR_UNTRUSTED_APP_RSC_INTELLIGENCE_FREEZES_INTELLIGENT_REDISTRIBUTION; RESTART_FENCES_ALL_PRE_RESTART_REDISTRIBUTION_DECISIONS; VALID_FRESH_FOUNDATION_ENVELOPE_AND_PROTECTED_MINIMA_REMAIN_REQUIRED; PEER_RESOURCE_SEIZURE_DENIED; UNKNOWN_RESOURCE_TRUTH_DENIES_RISK_INCREASING_REALLOCATION",
        AiRepairRecoveryPolicy = "DETECT->CONTAIN->INVESTIGATE->REPAIR_IN_ISOLATION->INDEPENDENT_VALIDATION->CONTROLLED_REVIVAL; R1_PREAUTHORIZED_NONSEMANTIC_ONLY; R2_OWNER_APPROVAL_BEFORE_REVIVAL; R3_OWNER_GOVERNANCE_MANDATORY; APP_RSC_CANNOT_SELF_GRANT_FOUNDATION_RESOURCE_AUTHORITY",
        ReplacementRemovalPolicy = "RECONCILE_PEER_CLAIMS_COORDINATION_EPOCHS_FOUNDATION_PROJECTIONS_GRANTS_ROUTES_PERMISSIONS_RESOURCES_PERSISTED_STATE_DURABLE_DECISION_FENCES_EVIDENCE_AND_DEPENDENCIES; NO_SIBLING_INHERITS_APP_RSC_OR_FOUNDATION_AUTHORITY_BY_DEFAULT"
    };
}
