<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.TradingGuardian.Contracts</AssemblyName><RootNamespace>Falcon.FSATS.TradingGuardian.Contracts</RootNamespace><PackageId>Falcon.FSATS.TradingGuardian.Contracts</PackageId><IsPackable>true</IsPackable></PropertyGroup></Project>
