<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Falcon.FSATS.FoundationBindings</AssemblyName>
    <RootNamespace>Falcon.FSATS.FoundationBindings</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Falcon.FSATS.Primitives/Falcon.FSATS.Primitives.csproj" />
  </ItemGroup>
</Project>
