<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Falcon.FSATS.FSTSimA.Host</AssemblyName><RootNamespace>Falcon.FSATS.FSTSimA.Host</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Contracts\Falcon.FSATS.FSTSimA.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Domain\Falcon.FSATS.FSTSimA.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Application\Falcon.FSATS.FSTSimA.Application.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Infrastructure\Falcon.FSATS.FSTSimA.Infrastructure.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Awareness\Falcon.FSATS.FSTSimA.Awareness.csproj" /></ItemGroup></Project>
