<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Falcon.Stage6.WP10.Verifier</AssemblyName>
    <RootNamespace>Falcon.Stage6.WP10.Verifier</RootNamespace>
    <StartupObject>Falcon.Stage6.WP10.Verifier.ProgramV3</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>
</Project>
