namespace Falcon.FSATS.TradingGuardian.Application;

public sealed record ApplicationResourceProfile(
    string MinimumSafe,
    string Desired,
    string CeilingOrUsefulBound,
    string PressureSemantics,
    string Reclaimability,
    string DegradedOrSheddingSemantics,
    string RestorationSemantics);

public sealed record ApplicationManifest(
    string ApplicationId, string PackageId, string Version, string Owner, string Purpose,
    string PackageProvenance, string PackageIntegrityPolicy, string CompatibilityPolicy, string LifecycleState, string OwnedBusinessBoundary,
    string MsaId, IReadOnlyList<string> LsaIds, IReadOnlyList<string> CsaIds, string CsaEligibilityPolicy,
    IReadOnlyList<string> DeclaredDependencies, IReadOnlyList<string> RequiredFoundationCapabilities, IReadOnlyList<string> RequiredFoundationContracts,
    IReadOnlyList<string> ProvidedCapabilities, IReadOnlyList<string> DeclaredConsumers, IReadOnlyList<string> Permissions, IReadOnlyList<string> AuthorityRequests,
    string SecurityProfile, string ResourcePolicy, string PersistencePolicy, string CommunicationPolicy, string ConfigurationPolicy, string EvidencePolicy,
    string LifecyclePolicy, string HealthPolicy, string FailureContainmentPolicy, string SelfDevelopmentPolicy, string GuardianRequirement,
    string ProtectionInterface, string RollbackPlan, IReadOnlyList<string> ProhibitedResponsibilities,
    bool RuntimeAuthorized, bool ProtectionRouteBound)
{
    public ApplicationResourceProfile ResourceProfile { get; init; } = new("UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED");
    public string SafetyContinuityPolicy { get; init; } = "UNDECLARED";
    public string AiRepairRecoveryPolicy { get; init; } = "UNDECLARED";
    public string ReplacementRemovalPolicy { get; init; } = "UNDECLARED";
    public string ManifestGeneration { get; init; } = "PART3_BASE_MANIFEST_GENERATION";
    public string ManifestGenerationLifecycleState { get; init; } = "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE";
    public string CurrentGovernedApplicationState { get; init; } = "PART8_OWNER_ACCEPTED_AND_CLOSED_NOT_RUNTIME_ACTIVE";
    public bool CurrentGovernedStateGrantsRuntimeAuthority { get; init; } = false;
}

public static class TradingGuardianManifest
{
    public static ApplicationManifest Current { get; } = new(
        "FSATS-TRADING-GUARDIAN", "Falcon.FSATS.TradingGuardian", "0.1.0-part3", "FSATS Application Workstream",
        "Independent trading protection, crisis and recovery Application.",
        "APPLICATION_DEVELOPMENT_GOVERNED_SOURCE", "EXACT_BUILD_ARTIFACT_IDENTITY_AND_DIGEST_REQUIRED_BEFORE_ADMISSION",
        "CONTRACT_VERSION_AND_FOUNDATION_BINDING_MUST_BE_EXPLICITLY_VERIFIED", "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE",
        "TRADING_PROTECTION_INCIDENT_CONTAINMENT_AND_RECOVERY_ORCHESTRATION_ONLY",
        "MSA-GUARDIAN-01", Array.AsReadOnly(Enumerable.Range(1, 4).Select(i => $"G-LSA-{i:00}").ToArray()), Array.AsReadOnly(new[] { "CSA-G01-01" }),
        "CSA_ONLY_FOR_OWNER_ACCEPTED_INCIDENT_CLASSIFIER_WITH_PARENT_G_LSA_01",
        Array.AsReadOnly(new[] { "TRADING:GOVERNED_PROTECTION_TARGET", "FSAPMA:GOVERNED_INCIDENT_EVIDENCE", "APP-RSC:GOVERNED_RESOURCE_COORDINATION" }),
        Array.AsReadOnly(new[] { "ApplicationLifecycle", "Communication", "Evidence", "Resources", "Security", "Persistence" }),
        Array.AsReadOnly(new[] { "APP-001", "CON-023", "FIL", "SERVICE_BUS", "SECURITY", "EVIDENCE", "LIFECYCLE", "PERSISTENCE" }),
        Array.AsReadOnly(new[] { "PROTECTION_COMMAND", "INCIDENT_CLASSIFICATION", "TRADING_CONTAINMENT_DECISION", "RECOVERY_COORDINATION", "APPLICATION_DURABLE_RESTART_RECONSTRUCTION" }),
        Array.AsReadOnly(new[] { "AUTHORIZED_FSATS_TRADING_PROTECTION_TARGETS_ONLY" }),
        Array.AsReadOnly(new[] { "PROTECTION_DECISION_STATE", "GOVERNED_ROUTE_CONSUMPTION", "GOVERNED_PERSISTENCE_PORT_ONLY", "NO_TRADING_STRATEGY_OR_BROKER_TRUTH_OWNERSHIP" }),
        Array.AsReadOnly(new[] { "NO_RUNTIME_AUTHORITY_ACTIVE", "NO_PROTECTION_ROUTE_BINDING_ACTIVE", "NO_PRODUCTION_PERSISTENCE_BINDING_AUTHORITY_ACTIVE" }),
        "DENY_UNDECLARED_TARGET_ROUTE_AUTHORITY_AND_RELEASE; PROTECTION_EVIDENCE_MUST_BE_ATTRIBUTABLE_AND_RECONSTRUCTABLE; NO_CUSTOMER_OR_USER_IDENTITY_OWNERSHIP",
        "USE_ONLY_FOUNDATION_ADMITTED_ALLOCATION; PROTECTIVE_MINIMUM_SURVIVAL_PRIORITY_WITHIN_ADMITTED_SCOPE; NO_FOUNDATION_RESOURCE_AUTHORITY",
        "APPLICATION_OWNED_INCIDENT_PROTECTION_IDEMPOTENCY_AND_RECOVERY_STATE_HAVE_VERSIONED_DIGEST_BOUND_RECONSTRUCTION_SEMANTICS; UNRESOLVED_PROTECTION_OUTCOMES_SURVIVE_RESTART_AS_RECONCILIATION_REQUIRED; GOVERNED_FOUNDATION_PERSISTENCE_BINDING_REQUIRED_FOR_RUNTIME; NO_LOCAL_PRODUCTION_SUBSTITUTE",
        "DECLARED_GOVERNED_PROTECTION_AND_EVIDENCE_ROUTES_ONLY; DUPLICATES_IDEMPOTENT; UNKNOWN_OUTCOME_REQUIRES_RECONCILIATION",
        "GOVERNED_PROTECTION_POLICY_CONFIGURATION; MATERIAL_SCOPE_OR_AUTHORITY_CHANGE_REQUIRES_REVIEW",
        "COMMAND_REQUEST_FINGERPRINT_EVIDENCE_DECISION_OUTCOME_RECOVERY_DURABILITY_AND_RECONSTRUCTION_CHAIN_MUST_REMAIN_ATTRIBUTABLE",
        "LIFECYCLE_STATES_DISTINCT; PART3_DOES_NOT_GRANT_PROTECTION_ROUTE_ACTIVATION; RESTART_IS_NOT_RELEASE",
        "REPORT_INCIDENT_SCOPE_PROTECTION_EPOCH_ROUTE_READINESS_MSA_LSA_CSA_RECOVERY_AND_RECONSTRUCTION_TRUST_STATE",
        "MINIMUM_NECESSARY_CONTAINMENT_WHEN_LOCALITY_PROVEN; EXPAND_ON_UNKNOWN_BLAST_RADIUS; BROKER_ACCOUNT_FAILURE_NOT_AUTOMATICALLY_BROKER_OR_APPLICATION_FAILURE",
        "CSA_TO_PARENT_LSA_TO_MSA_TO_FSA_TO_SEPARATE_OWNER_GOVERNANCE; NO_CSA_PROTECTION_AUTHORITY_EXPANSION",
        "THIS_APPLICATION_IS_THE_FSATS_TRADING_GUARDIAN; IT_CANNOT_SELF_GRANT_FOUNDATION_OR_OWNER_AUTHORITY",
        "GOVERNED_PROTECTION_COMMAND_OUTCOME_WITH_EXACT_TARGET_EPOCH_IDEMPOTENCY_FINGERPRINT_EVIDENCE_AND_RESTART_RECONCILIATION_BINDING",
        "ROLLBACK_OR_APPROVED_CORRECTIVE_ACTION_MUST_PRESERVE_RESTRICTION_INCIDENT_EVIDENCE_DURABLE_IDEMPOTENCY_AND_UNRESOLVED_PROTECTION_TRUTH; RESTART_IS_NOT_RELEASE",
        Array.AsReadOnly(new[] { "TradingStrategyOwnership", "TradingExecutionTruthOwnership", "ProviderTruthOwnership", "FoundationGovernance", "FoundationPersistenceImplementation", "CustomerUserIdentityOwnership" }),
        RuntimeAuthorized: false, ProtectionRouteBound: false)
    {
        ResourceProfile = new(
            "DETERMINISTIC_PROTECTION_RESTRICTION_INCIDENT_OWNERSHIP_DURABLE_RECONSTRUCTION_AND_RECOVERY_TRACKING_WITHIN_FOUNDATION_ADMITTED_ALLOCATION",
            "NORMAL_INCIDENT_CLASSIFICATION_PROTECTION_MONITORING_AND_RECOVERY_COORDINATION_CAPACITY_WITHIN_ADMITTED_ALLOCATION",
            "FOUNDATION_ADMITTED_CEILING_OR_USEFUL_BOUND_ONLY_NEVER_GUARDIAN_MINTED",
            "PRESSURE_MUST_PRESERVE_VALID_HARD_PROTECTIONS_OPEN_RESTRICTION_OWNERSHIP_AND_UNRESOLVED_DURABLE_OUTCOMES_BEFORE_OPTIONAL_INTELLIGENCE",
            "AI_ASSISTED_CLASSIFICATION_ANALYTICS_AND_NONESSENTIAL_DIAGNOSTICS_ARE_RECLAIMABLE_BEFORE_DETERMINISTIC_PROTECTION",
            "SHED_OPTIONAL_INTELLIGENCE; NEVER_EVICT_UNRESOLVED_PROTECTION_RESTRICTION_OR_IDEMPOTENCY_TRUTH",
            "RESTORE_ONLY_AFTER_FOUNDATION_ENVELOPE_PROTECTION_EPOCH_ROUTE_BINDING_INCIDENT_TRUST_AND_REQUIRED_RECONSTRUCTED_PROTECTION_STATE_ARE_REVALIDATED"),
        SafetyContinuityPolicy = "KILL_OF_GUARDIAN_AI_DOES_NOT_REVOKE_VALID_DETERMINISTIC_HARD_PROTECTIONS_OUTSIDE_THE_BLAST_RADIUS; UNRESOLVED_RESTRICTIONS_REMAIN_OWNED_ACROSS_RESTART; MINIMUM_NECESSARY_CONTAINMENT; UNKNOWN_BLAST_RADIUS_EXPANDS; NO_SELF_RELEASE",
        AiRepairRecoveryPolicy = "DETECT->CONTAIN->INVESTIGATE->REPAIR_IN_ISOLATION->INDEPENDENT_VALIDATION->CONTROLLED_REVIVAL; R1_PREAUTHORIZED_NONSEMANTIC_ONLY; R2_OWNER_APPROVAL_BEFORE_REVIVAL; R3_OWNER_GOVERNANCE_MANDATORY",
        ReplacementRemovalPolicy = "RECONCILE_INCIDENTS_RESTRICTIONS_PROTECTION_EPOCHS_ROUTES_PERMISSIONS_RESOURCES_PERSISTED_STATE_DURABLE_TOMBSTONES_EVIDENCE_OPEN_OBLIGATIONS_AND_DEPENDENCIES; NO_SIBLING_INHERITS_GUARDIAN_AUTHORITY_BY_DEFAULT"
    };
}
