<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.TradingGuardian.Application</AssemblyName><RootNamespace>Falcon.FSATS.TradingGuardian.Application</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Contracts\Falcon.FSATS.TradingGuardian.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Domain\Falcon.FSATS.TradingGuardian.Domain.csproj" /></ItemGroup></Project>
