namespace Falcon.FSATS.FSTSimA.Application;

public sealed record ApplicationResourceProfile(
    string MinimumSafe,
    string Desired,
    string CeilingOrUsefulBound,
    string PressureSemantics,
    string Reclaimability,
    string DegradedOrSheddingSemantics,
    string RestorationSemantics);

public sealed record ApplicationManifest(
    string ApplicationId, string PackageId, string Version, string Owner, string Purpose,
    string PackageProvenance, string PackageIntegrityPolicy, string CompatibilityPolicy, string LifecycleState, string OwnedBusinessBoundary,
    string MsaId, IReadOnlyList<string> LsaIds, IReadOnlyList<string> CsaIds, string CsaEligibilityPolicy,
    IReadOnlyList<string> DeclaredDependencies, IReadOnlyList<string> RequiredFoundationCapabilities, IReadOnlyList<string> RequiredFoundationContracts,
    IReadOnlyList<string> ProvidedCapabilities, IReadOnlyList<string> DeclaredConsumers, IReadOnlyList<string> Permissions, IReadOnlyList<string> AuthorityRequests,
    string SecurityProfile, string ResourcePolicy, string PersistencePolicy, string CommunicationPolicy, string ConfigurationPolicy, string EvidencePolicy,
    string LifecyclePolicy, string HealthPolicy, string FailureContainmentPolicy, string SelfDevelopmentPolicy, string GuardianRequirement,
    string ProtectionInterface, string RollbackPlan,
    bool RuntimeAuthorized, bool OperationalEgressAuthorized, bool PaperAuthority)
{
    public ApplicationResourceProfile ResourceProfile { get; init; } = new("UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED");
    public string SafetyContinuityPolicy { get; init; } = "UNDECLARED";
    public string AiRepairRecoveryPolicy { get; init; } = "UNDECLARED";
    public string ReplacementRemovalPolicy { get; init; } = "UNDECLARED";
    public string ManifestGeneration { get; init; } = "PART3_BASE_MANIFEST_GENERATION";
    public string ManifestGenerationLifecycleState { get; init; } = "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE";
    public string CurrentGovernedApplicationState { get; init; } = "PART9_OWNER_ACCEPTED_AND_CLOSED_NOT_RUNTIME_ACTIVE";
    public bool CurrentGovernedStateGrantsRuntimeAuthority { get; init; } = false;
}

public static class FSTSimAManifest
{
    public static ApplicationManifest Current { get; } = new(
        "FSATS-FSTSIMA", "Falcon.FSATS.FSTSimA", "0.1.0-part3", "FSATS Application Workstream",
        "Non-Live simulation, synthetic market, fault injection, calibration and independent validation evidence.",
        "APPLICATION_DEVELOPMENT_GOVERNED_SOURCE", "EXACT_BUILD_ARTIFACT_IDENTITY_AND_DIGEST_REQUIRED_BEFORE_ADMISSION",
        "CONTRACT_VERSION_AND_FOUNDATION_BINDING_MUST_BE_EXPLICITLY_VERIFIED", "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE",
        "NON_LIVE_SIMULATION_SYNTHETIC_MARKET_FAULT_INJECTION_CALIBRATION_AND_VALIDATION_ONLY",
        "MSA-FSTSIMA-01", Array.AsReadOnly(Enumerable.Range(1, 8).Select(i => $"S-LSA-{i:00}").ToArray()), Array.AsReadOnly(new[] { "CSA-S02-01", "CSA-S07-01" }),
        "CSA_ONLY_FOR_OWNER_ACCEPTED_SYNTHETIC_MARKET_GENERATOR_AND_CALIBRATION_ENGINE_WITH_EXACT_PARENT_LSA",
        Array.AsReadOnly(new[] { "TRADING:VALIDATION_SUBJECT_CONTRACTS", "FSAPMA:REPLAY_OR_SYNTHETIC_DATA_INPUT_WHEN_AUTHORIZED", "APP-RSC:GOVERNED_RESOURCE_COORDINATION" }),
        Array.AsReadOnly(new[] { "ApplicationLifecycle", "Communication", "Evidence", "Resources", "Security", "Persistence" }),
        Array.AsReadOnly(new[] { "APP-001", "CON-023", "FIL", "SERVICE_BUS", "SECURITY", "EVIDENCE", "LIFECYCLE", "PERSISTENCE" }),
        Array.AsReadOnly(new[] { "SYNTHETIC_MARKET_GENERATION", "FAULT_INJECTION", "CALIBRATION", "INDEPENDENT_VALIDATION_EVIDENCE", "DIGITAL_CITY_GOVERNED_VALIDATION", "APPLICATION_DURABLE_CHECKPOINT_RECONSTRUCTION" }),
        Array.AsReadOnly(new[] { "AUTHORIZED_VALIDATION_WORKFLOWS_ONLY" }),
        Array.AsReadOnly(new[] { "NON_LIVE_STATE_ONLY", "GOVERNED_PERSISTENCE_PORT_ONLY", "NO_LIVE_CREDENTIAL_OR_ROUTE_ACQUISITION", "NO_OPERATIONAL_TRUTH_PROMOTION" }),
        Array.AsReadOnly(new[] { "NO_RUNTIME_AUTHORITY_ACTIVE", "NO_OPERATIONAL_EGRESS_AUTHORITY_ACTIVE", "NO_PAPER_AUTHORITY_ACTIVE", "NO_PRODUCTION_PERSISTENCE_BINDING_AUTHORITY_ACTIVE" }),
        "NON_LIVE_ONLY; DENY_LIVE_CREDENTIAL_ROUTE_AND_OPERATIONAL_AUTHORITY; SYNTHETIC_REPLAY_TEST_TRUTH_MUST_REMAIN_EXPLICIT",
        "USE_ONLY_FOUNDATION_ADMITTED_ALLOCATION; VALIDATION_LOAD_MUST_NOT_BYPASS_OTHER_APPLICATION_PROTECTION_FLOORS",
        "APPLICATION_OWNED_SIMULATION_RUN_CHECKPOINT_AND_VALIDATION_EVIDENCE_HAVE_VERSIONED_DIGEST_BOUND_RECONSTRUCTION_SEMANTICS; INTERRUPTED_OR_UNCOMMITTED_RUNS_CANNOT_QUALIFY; GOVERNED_FOUNDATION_PERSISTENCE_BINDING_REQUIRED_FOR_RUNTIME; NO_LOCAL_PRODUCTION_SUBSTITUTE",
        "DECLARED_NON_LIVE_GOVERNED_ROUTES_ONLY; NO_LIVE_OR_PAPER_BINDING_IN_PART3",
        "GOVERNED_SIMULATION_SEED_SCENARIO_CALIBRATION_AND_FAULT_CONFIGURATION; MATERIAL_CHANGE_REQUIRES_REVIEW",
        "REPRODUCIBLE_SEED_SCENARIO_INPUT_OUTPUT_CALIBRATION_VALIDATION_CHECKPOINT_DURABILITY_AND_RECONSTRUCTION_PROVENANCE_REQUIRED",
        "LIFECYCLE_STATES_DISTINCT; PART3_DOES_NOT_GRANT_RUNTIME_PAPER_SHADOW_OR_LIVE_ACTIVATION; RESTART_DOES_NOT_COMPLETE_AN_INTERRUPTED_RUN",
        "REPORT_SIMULATION_READINESS_CALIBRATION_VALIDATION_MSA_LSA_CSA_NON_LIVE_ISOLATION_AND_RECONSTRUCTION_STATE",
        "SIMULATION_OR_VALIDATION_FAILURE_CONTAINED_TO_FSTSIMA; MUST_NOT_COMPROMISE_TRADING_OR_PROMOTE_FALSE_OPERATIONAL_TRUTH",
        "CSA_TO_PARENT_LSA_TO_MSA_TO_FSA_TO_SEPARATE_OWNER_GOVERNANCE; NO_SELF_PROMOTION_FROM_VALIDATION_TO_PRODUCTION",
        "TRADING_GUARDIAN_DOES_NOT_GAIN_SIMULATION_BUSINESS_OWNERSHIP; ANY_SAFETY_INCIDENT_ROUTE_REMAINS_GOVERNED",
        "NON_LIVE_EVIDENCE_AND_STATUS_INTERFACES_ONLY_UNLESS_SEPARATELY_AUTHORIZED",
        "ROLLBACK_OR_APPROVED_CORRECTIVE_ACTION_MUST_PRESERVE_REPRODUCIBILITY_DURABLE_CHECKPOINT_EVIDENCE_AND_NON_LIVE_ISOLATION",
        RuntimeAuthorized: false, OperationalEgressAuthorized: false, PaperAuthority: false)
    {
        ResourceProfile = new(
            "MINIMUM_CAPACITY_TO_PRESERVE_REPRODUCIBILITY_COMMITTED_EVIDENCE_DURABLE_CHECKPOINTS_AND_ISOLATED_VALIDATION_STATE_WITHIN_FOUNDATION_ADMITTED_ALLOCATION",
            "NORMAL_SYNTHETIC_MARKET_FAULT_INJECTION_CALIBRATION_AND_VALIDATION_CAPACITY_WITHIN_ADMITTED_ALLOCATION",
            "FOUNDATION_ADMITTED_CEILING_OR_USEFUL_BOUND_ONLY_NEVER_SIMULATOR_MINTED",
            "PRESSURE_MAY_REDUCE_SCENARIO_BREADTH_SAMPLE_COUNT_OR_PARALLELISM_BUT_MUST_NOT_CORRUPT_REPRODUCIBILITY_DURABLE_CHECKPOINTS_OR_NON_LIVE_ISOLATION",
            "OPTIONAL_SCENARIO_BREADTH_PARALLELISM_AND_EXPERIMENTAL_RUNS_ARE_RECLAIMABLE",
            "SHED_OPTIONAL_EXPERIMENTS_AND_PARALLELISM; NEVER_EVICT_COMMITTED_EVIDENCE_NEEDED_FOR_REPRODUCIBILITY_OR_MISCLASSIFY_PARTIAL_RUNS",
            "RESTORE_ONLY_AFTER_FOUNDATION_ENVELOPE_AND_VALIDATION_REPRODUCIBILITY_RECONSTRUCTION_STATE_ARE_REVALIDATED"),
        SafetyContinuityPolicy = "FAILURE_OR_KILL_INSIDE_FSTSIMA_REMAINS_CONTAINED_TO_NON_LIVE_SCOPE; RESTART_CLASSIFIES_UNCOMMITTED_RUNS_AS_INTERRUPTED; SIMULATION_REPLAY_TEST_IDENTITIES_NEVER_BECOME_OPERATIONAL_TRUTH; UNKNOWN_BLAST_RADIUS_EXPANDS_WITHOUT_GRANTING_LIVE_AUTHORITY",
        AiRepairRecoveryPolicy = "DETECT->CONTAIN->INVESTIGATE->REPAIR_IN_ISOLATION->INDEPENDENT_VALIDATION->CONTROLLED_REVIVAL; R1_PREAUTHORIZED_NONSEMANTIC_ONLY; R2_OWNER_APPROVAL_BEFORE_REVIVAL; R3_OWNER_GOVERNANCE_MANDATORY; VALIDATION_DOES_NOT_SELF_PROMOTE_TO_PRODUCTION",
        ReplacementRemovalPolicy = "RECONCILE_SEEDS_SCENARIOS_CALIBRATION_STATE_VALIDATION_EVIDENCE_DURABLE_CHECKPOINTS_ROUTES_PERMISSIONS_RESOURCES_PERSISTENCE_AND_DEPENDENCIES; REMOVAL_MUST_NOT_DAMAGE_TRADING_OR_PROMOTE_SIMULATION_STATE"
    };
}
