<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Falcon.BaselineIntegrity.Verifier</AssemblyName>
    <RootNamespace>Falcon.BaselineIntegrity.Verifier</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundation.Enabling\Foundation.Enabling.csproj" />
  </ItemGroup>
</Project>