export const messages = {
  ar: {
    brand:'FALCON OS', home:'الرئيسية', applications:'التطبيقات', about:'حول Falcon', support:'الدعم', signIn:'تسجيل الدخول', createAccount:'إنشاء حساب',
    heroTitle:'نظام تشغيل مالي ذاتي الوعي', heroAccent:'يحمي رأس المال ويديره وينمّيه', heroText:'Falcon منصة مالية متعددة التطبيقات تجمع الذكاء المنضبط، إدارة المخاطر، والتحكم الواضح ضمن نظام واحد.', explore:'استكشف التطبيقات', learnVision:'تعرّف على الرؤية', appsTitle:'تطبيقات Falcon', appsText:'كل تطبيق مستقل في تخصصه ويعمل ضمن حدود Falcon وحوكمته.',
    trading:'FSATS Trading', tradingDesc:'تجربة التداول والتحليل الذكي وإدارة المحفظة.', ai:'AI Prediction', aiDesc:'قدرات تنبؤ وتحليل متخصصة عندما تصبح متاحة.', risk:'Risk Management', riskDesc:'إدارة المخاطر وحماية رأس المال ضمن صلاحياتها.', provider:'Provider Management', providerDesc:'إدارة مصادر البيانات والتكاملات.', communication:'Communication', communicationDesc:'التواصل والإشعارات المشتركة.', coming:'قريبًا', discover:'استكشف التطبيق',
    welcome:'مرحبًا بك في Falcon', email:'البريد الإلكتروني أو اسم المستخدم', password:'كلمة المرور', remember:'تذكرني', forgot:'نسيت كلمة المرور؟', myApps:'تطبيقاتي', availableApps:'تطبيقات متاحة', open:'فتح', subscribe:'اشتراك', manageApps:'إدارة التطبيقات',
    fsatsHero:'تداول ذكي. رؤية أعمق.', fsatsText:'واجهة تداول تركّز على السوق، المحفظة، التحليل، وFalcon AI دون كشف تعقيد البنية الداخلية.', start:'ابدأ الآن', dashboard:'لوحة التحكم', markets:'الأسواق', portfolio:'المحفظة', positions:'المراكز', activity:'النشاط', performance:'الأداء', notifications:'التنبيهات', settings:'الإعدادات', falconAI:'Falcon AI',
    totalValue:'إجمالي قيمة المحفظة', todayPL:'الربح / الخسارة اليوم', totalPL:'إجمالي الأداء', available:'المتاح', chart:'الرسم البياني', recentTrades:'أحدث الصفقات', quickSummary:'ملخص Falcon', askFalcon:'اسأل Falcon', customize:'تخصيص لوحة التحكم', resetLayout:'إعادة الافتراضي', manageWidgets:'إدارة العناصر', restore:'إظهار', hide:'إخفاء', demo:'معاينة تجريبية غير مرتبطة ببيانات حية',
    ownerCenter:'مركز قيادة المالك', systemOverview:'نظرة عامة على النظام', systemHealth:'صحة النظام', activeApps:'التطبيقات العاملة', activeUsers:'المستخدمون النشطون', incidents:'الحوادث المفتوحة', approvals:'الموافقات المعلقة', needsAttention:'تحتاج انتباه', systemChat:'محادثة مع Falcon', audit:'سجل النشاط', users:'المستخدمون', backup:'النسخ الاحتياطي', security:'الأمن', controls:'التحكم', simulator:'المحاكاة والتشخيص', noTradingOwner:'واجهة المالك للتحكم بالنظام وليست واجهة تداول.', language:'اللغة',
    active:'نشط', inactive:'غير نشط', trades:'الصفقات', history:'السجل', user:'مستخدم', customer:'العميل', view:'عرض', review:'مراجعة', evidence:'الأدلة', information:'معلومات', systemController:'متحكم النظام', ownerOnly:'للمالك فقط',
    portfolioTruthNote:'القيم المعروضة تأتي من إسقاط FSATS كما هي. القيمة غير المتوفرة لا تعني صفرًا، والبيانات القديمة لا تعني بيانات حالية.',
    orderTruthNote:'طلب الأمر ≠ قبوله ≠ تنفيذه جزئيًا ≠ تنفيذه بالكامل.',
    orderSide_BUY:'شراء', orderSide_SELL:'بيع', 'orderSide_—':'—',
    orderState_REQUESTED:'مطلوب', orderState_ACCEPTED:'مقبول', orderState_PARTIALLY_FILLED:'منفذ جزئيًا', orderState_FILLED:'منفذ بالكامل', orderState_CANCEL_REQUESTED:'إلغاء مطلوب', orderState_CANCELLED:'ملغى', orderState_REPLACEMENT_REQUESTED:'استبدال مطلوب', orderState_REPLACED:'مستبدل', orderState_REJECTED:'مرفوض', orderState_UNKNOWN_BROKER_OUTCOME:'نتيجة البروكر غير معروفة',
    truth_CURRENT:'الحالية', truth_LAST_KNOWN:'آخر حالة معروفة', truth_STALE:'قديمة', truth_PARTIAL:'ناقصة', truth_UNKNOWN:'غير معروفة', truth_UNAVAILABLE:'غير متوفرة', truth_DEGRADED:'متدهورة', truth_UNTRUSTED:'غير موثوقة', truth_SIMULATION:'محاكاة', truth_REPLAY:'إعادة تشغيل',
    priority_HIGH:'عالية', priority_MEDIUM:'متوسطة', priority_LOW:'منخفضة',
    incidentConversation:'محادثة الحادث', incidentStatus_OPEN:'مفتوح', incidentStatus_RESOLVED:'تم الحل', incidentStatus_RECONCILING:'قيد المطابقة',
    supportAgent:'الدعم', supportTakeoverActive:'تم استلام المحادثة من الدعم', supportIdentityNotice:'أنت تتحدث الآن مع موظف دعم بشري بشكل واضح. Falcon يراقب بصمت لحفظ سياق الحادث ولا يتحدث باسم الدعم.', supportEscalated:'تم تصعيد الحالة إلى الدعم', falconStillActive:'Falcon ما زال يتابع معك داخل نفس الحادث حتى يحصل استلام صريح من الدعم.',
    actionRequired:'إجراء مطلوب', incidentFollowupGeneric:'نحتاج تحديثًا منك لإكمال معالجة الحادث.', incidentTimeline:'الخط الزمني للحادث', uploadOneScreenshot:'إرفاق لقطة شاشة واحدة', voiceConversation:'محادثة صوتية', minimizeIncident:'تصغير الحادث', restoreIncident:'إعادة فتح الحادث',
    incidentTruthNotice:'لا ترسل كلمات مرور أو مفاتيح API أو أسرارًا هنا. لقطة الشاشة ملاحظة وليست تأكيدًا من API البروكر. الاستلام أو الرد أو التصعيد لا يعني حل الحادث.',
    incidentUnavailableActionsNotice:'بعض إجراءات الحادث غير متاحة حتى يكتمل الربط الآمن والمخول. ظهور الزر لا يعني أن الإجراء متاح أو تم تنفيذه.',
    voiceListeningActive:'الاستماع الصوتي للحادث فعال', stopVoiceListening:'إيقاف الاستماع الصوتي', replyToSupport:'اكتب ردك للدعم…', replyToFalcon:'اكتب ردك لـFalcon…', transcriptEdited:'تم تعديل النص', incidentResolutionNotice:'يبقى الحادث مفتوحًا حتى يؤكد المصدر المخول حالته. عرض الرسالة أو الرد عليها لا يحولها إلى حالة محلولة.',
    controlTruthNotice:'أزرار التحكم ترسل طلبات فقط حتى يؤكد النظام المالك النتيجة المخولة.', ownerAppTruthNotice:'حالة النظام/التطبيق فقط. لا يتم إنشاء أو استنتاج بيانات تداول هنا.', supportIncidentAccessNotice:'يمكن للدعم مشاهدة محادثة الحادث، وبعد استلام صريح ومرئي يمكنه التواصل مباشرة مع العميل بهوية دعم بشرية.', supportAuthorityNotice:'استلام الدعم لا يمنح صلاحية تنفيذ صفقات أو التحكم بالمحفظة ولا يعني أن الحادث تم حله.', supportTakeoverUnavailable:'استلام الدعم غير متاح حتى يتم التحقق من هوية جلسة الدعم وصلاحيتها بشكل مخول.',
    fiveMinuteNoReplyFollowup:'متابعة بعد خمس دقائق دون رد', fiveMinuteNoReplyTruthNotice:'عدم وجود رد بعد مشاهدة الرسالة حقيقة قابلة للملاحظة فقط، ولا يعني أن العميل تجاهل الرسالة أو فهمها أو رفضها.',
    takeOverAsSupport:'استلام كدعم', pendingGovernedDecision:'قرار محكوم بانتظار المراجعة', approvalTruthNotice:'الطلب ومصدر الصلاحية والنتيجة حالات منفصلة. الضغط على زر لا يعني اكتمال الإجراء.',
    auditIncidentEvidenceOpened:'تم فتح أدلة حادث النظام.', auditAppProjectionUpdated:'تم تحديث إسقاط حالة التطبيق.', auditBackupProjectionReceived:'تم استلام إسقاط حالة النسخ الاحتياطي.', simulationDiagnostics:'عرض المحاكاة والتشخيص', simulatorTruthNotice:'هذه الواجهة غير موجودة في تجربة المستخدم العادية. حقيقة السيميوليتر تظل مملوكة للتطبيق ولا ينشئها Web.',
    usEquities:'الأسهم الأمريكية', cryptoSpot:'الكريبتو الفوري', marketOpen:'مفتوح', aroundClock:'24/7', preview:'معاينة', assetSearch:'بحث عن أصل', marketDisplayNotice:'بيانات السوق هنا للعرض فقط ولا تدخل إلى FSATS كبيانات تشغيلية أو تحليلية.', providerRoutesPending:'مسارات مزودي العرض مضافة بشكل مقفول حتى اكتمال الحوكمة والتفعيل.',
    analysisShort:'قصير المدى', analysisMedium:'متوسط المدى', analysisLong:'طويل المدى', strategies:'الاستراتيجيات', schools:'المدارس', synthesis:'الخلاصة', showFullAnalysis:'عرض التحليل الكامل', analysisTruthNotice:'Falcon يعرض تحليل FSATS ولا يصبح مالك حقيقة التحليل أو سلطة تنفيذ.', noAnalysisValue:'غير متوفر من المصدر',
    voiceGeneralEmergency:'يوجد مشكلة في حسابك وتتطلب انتباهك. الرجاء فتح المحادثة والمتابعة معي.'
  },
  en: {
    brand:'FALCON OS', home:'Home', applications:'Applications', about:'About Falcon', support:'Support', signIn:'Sign in', createAccount:'Create account',
    heroTitle:'A self-aware financial operating system', heroAccent:'Protect. Manage. Grow capital.', heroText:'Falcon is a multi-application financial platform built around disciplined intelligence, risk stewardship, and explicit control.', explore:'Explore applications', learnVision:'Explore the vision', appsTitle:'Falcon Applications', appsText:'Each application remains independently scoped while operating within Falcon governance.',
    trading:'FSATS Trading', tradingDesc:'Intelligent trading, analysis, portfolio and activity experience.', ai:'AI Prediction', aiDesc:'Specialized prediction and analysis capabilities when available.', risk:'Risk Management', riskDesc:'Capital-protection and risk capabilities within governed authority.', provider:'Provider Management', providerDesc:'Data-provider and integration management.', communication:'Communication', communicationDesc:'Shared communication and notification capabilities.', coming:'Coming soon', discover:'Explore app',
    welcome:'Welcome to Falcon', email:'Email or username', password:'Password', remember:'Remember me', forgot:'Forgot password?', myApps:'My Applications', availableApps:'Available Applications', open:'Open', subscribe:'Subscribe', manageApps:'Manage Applications',
    fsatsHero:'Smarter trading. Deeper perspective.', fsatsText:'A trading experience focused on markets, portfolio, analysis and Falcon AI without exposing internal routing complexity.', start:'Start now', dashboard:'Dashboard', markets:'Markets', portfolio:'Portfolio', positions:'Positions', activity:'Activity', performance:'Performance', notifications:'Notifications', settings:'Settings', falconAI:'Falcon AI',
    totalValue:'Portfolio Value', todayPL:'Today P/L', totalPL:'Total Performance', available:'Available', chart:'Chart', recentTrades:'Recent Trades', quickSummary:'Falcon Summary', askFalcon:'Ask Falcon', customize:'Customize dashboard', resetLayout:'Reset layout', manageWidgets:'Manage widgets', restore:'Restore', hide:'Hide', demo:'Development preview, not live financial data',
    ownerCenter:'Owner Command Center', systemOverview:'System Overview', systemHealth:'System Health', activeApps:'Active Applications', activeUsers:'Active Users', incidents:'Open Incidents', approvals:'Pending Approvals', needsAttention:'Needs Your Attention', systemChat:'Chat with Falcon', audit:'Activity / Audit', users:'Users', backup:'Backup', security:'Security', controls:'Controls', simulator:'Simulator & Diagnostics', noTradingOwner:'The Owner surface controls the system. It is not a trading workspace.', language:'Language',
    active:'Active', inactive:'Inactive', trades:'Trades', history:'History', user:'User', customer:'Customer', view:'View', review:'Review', evidence:'Evidence', information:'Information', systemController:'System Controller', ownerOnly:'Owner only',
    portfolioTruthNote:'Displayed values come from the FSATS projection as supplied. Missing values are not zero and stale values are not current.', orderTruthNote:'ORDER REQUESTED ≠ ACCEPTED ≠ PARTIALLY FILLED ≠ FILLED.',
    orderSide_BUY:'Buy', orderSide_SELL:'Sell', 'orderSide_—':'—', orderState_REQUESTED:'Requested', orderState_ACCEPTED:'Accepted', orderState_PARTIALLY_FILLED:'Partially filled', orderState_FILLED:'Filled', orderState_CANCEL_REQUESTED:'Cancel requested', orderState_CANCELLED:'Cancelled', orderState_REPLACEMENT_REQUESTED:'Replacement requested', orderState_REPLACED:'Replaced', orderState_REJECTED:'Rejected', orderState_UNKNOWN_BROKER_OUTCOME:'Unknown broker outcome',
    truth_CURRENT:'Current', truth_LAST_KNOWN:'Last known', truth_STALE:'Stale', truth_PARTIAL:'Partial', truth_UNKNOWN:'Unknown', truth_UNAVAILABLE:'Unavailable', truth_DEGRADED:'Degraded', truth_UNTRUSTED:'Untrusted', truth_SIMULATION:'Simulation', truth_REPLAY:'Replay',
    priority_HIGH:'High', priority_MEDIUM:'Medium', priority_LOW:'Low', incidentConversation:'Incident conversation', incidentStatus_OPEN:'Open', incidentStatus_RESOLVED:'Resolved', incidentStatus_RECONCILING:'Reconciling',
    supportAgent:'Support', supportTakeoverActive:'Support has taken over the conversation', supportIdentityNotice:'You are now speaking with a clearly identified human Support agent. Falcon observes silently for incident continuity and does not speak as Support.', supportEscalated:'Incident escalated to Support', falconStillActive:'Falcon continues in the same incident until Support explicitly takes over.', actionRequired:'Action required', incidentFollowupGeneric:'We need an update from you to continue incident handling.', incidentTimeline:'Incident timeline', uploadOneScreenshot:'Upload one screenshot', voiceConversation:'Voice conversation', minimizeIncident:'Minimize incident', restoreIncident:'Restore incident', incidentTruthNotice:'Never send passwords, API keys or secrets here. A screenshot is an observation, not broker API confirmation. Delivery, reply, escalation or takeover does not resolve the incident.', incidentUnavailableActionsNotice:'Some incident actions remain unavailable until a secure authorized binding exists. A visible control does not mean the action is available or completed.', voiceListeningActive:'Incident voice listening is active', stopVoiceListening:'Stop voice listening', replyToSupport:'Reply to Support…', replyToFalcon:'Reply to Falcon…', transcriptEdited:'Transcript edited', incidentResolutionNotice:'The incident remains open until the authoritative source confirms its state. Viewing or replying does not resolve it.',
    controlTruthNotice:'Controls submit requests only until the owning system confirms an authoritative outcome.', ownerAppTruthNotice:'System/Application status only. No trading data is created or inferred here.', supportIncidentAccessNotice:'Support may view an incident conversation and, after explicit visible takeover, communicate directly with the customer under a human Support identity.', supportAuthorityNotice:'Support takeover does not create execution authority, portfolio control, or incident resolution.', supportTakeoverUnavailable:'Support takeover is unavailable until the Support session identity and capability are authoritatively verified.',
    fiveMinuteNoReplyFollowup:'5-minute no-reply follow-up', fiveMinuteNoReplyTruthNotice:'No reply after the message was viewed is an observable fact only; it does not mean the customer ignored, understood, or rejected it.',
    takeOverAsSupport:'Take over as Support', pendingGovernedDecision:'Pending governed decision', approvalTruthNotice:'Request, authority source and outcome remain separate. A UI click is not authoritative completion.', auditIncidentEvidenceOpened:'System incident evidence opened.', auditAppProjectionUpdated:'Application status projection updated.', auditBackupProjectionReceived:'Backup status projection received.', simulationDiagnostics:'Simulation / Shadow diagnostics presentation', simulatorTruthNotice:'This surface is absent from the regular customer experience. Simulator truth remains Application-owned and is not fabricated by Web.',
    usEquities:'US Equities', cryptoSpot:'Crypto Spot', marketOpen:'Open', aroundClock:'24/7', preview:'Preview', assetSearch:'Asset Search', marketDisplayNotice:'Market data here is presentation-only and never flows into FSATS as operational or analysis data.', providerRoutesPending:'Presentation provider routes are configured fail-closed pending governed activation.',
    analysisShort:'Short term', analysisMedium:'Medium term', analysisLong:'Long term', strategies:'Strategies', schools:'Schools', synthesis:'Synthesis', showFullAnalysis:'Show full analysis', analysisTruthNotice:'Falcon presents FSATS analysis and does not become the analysis truth owner or execution authority.', noAnalysisValue:'Unavailable from source', voiceGeneralEmergency:'There is a problem with your account that requires your attention. Please open the conversation and continue with me.'
  }
};

export function createI18n(initial='ar') {
  let lang = initial === 'en' ? 'en' : 'ar';
  return {
    get lang(){ return lang; },
    set(next){ lang = next === 'en' ? 'en' : 'ar'; document.documentElement.lang=lang; document.documentElement.dir=lang==='ar'?'rtl':'ltr'; localStorage.setItem('falcon.lang', lang); },
    t(key){ return messages[lang][key] ?? messages.en[key] ?? key; }
  };
}
