namespace Falcon.FSATS.FSAPMA.Application;

public sealed record ApplicationResourceProfile(
    string MinimumSafe,
    string Desired,
    string CeilingOrUsefulBound,
    string PressureSemantics,
    string Reclaimability,
    string DegradedOrSheddingSemantics,
    string RestorationSemantics);

public sealed record ApplicationManifest(
    string ApplicationId, string PackageId, string Version, string Owner, string Purpose,
    string PackageProvenance, string PackageIntegrityPolicy, string CompatibilityPolicy, string LifecycleState, string OwnedBusinessBoundary,
    string MsaId, IReadOnlyList<string> LsaIds, IReadOnlyList<string> CsaIds, string CsaEligibilityPolicy,
    IReadOnlyList<string> DeclaredDependencies, IReadOnlyList<string> RequiredFoundationCapabilities, IReadOnlyList<string> RequiredFoundationContracts,
    IReadOnlyList<string> ProvidedCapabilities, IReadOnlyList<string> DeclaredConsumers, IReadOnlyList<string> Permissions, IReadOnlyList<string> AuthorityRequests,
    string SecurityProfile, string ResourcePolicy, string PersistencePolicy, string CommunicationPolicy, string ConfigurationPolicy, string EvidencePolicy,
    string LifecyclePolicy, string HealthPolicy, string FailureContainmentPolicy, string SelfDevelopmentPolicy, string GuardianRequirement,
    string ProtectionInterface, string RollbackPlan, IReadOnlyList<string> CredentialReferenceRoles,
    bool RuntimeAuthorized, bool ProviderEgressAuthorized)
{
    public ApplicationResourceProfile ResourceProfile { get; init; } = new("UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED", "UNDECLARED");
    public string SafetyContinuityPolicy { get; init; } = "UNDECLARED";
    public string AiRepairRecoveryPolicy { get; init; } = "UNDECLARED";
    public string ReplacementRemovalPolicy { get; init; } = "UNDECLARED";
    public string ManifestGeneration { get; init; } = "PART3_BASE_MANIFEST_GENERATION";
    public string ManifestGenerationLifecycleState { get; init; } = "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE";
    public string CurrentGovernedApplicationState { get; init; } = "PART8_OWNER_ACCEPTED_AND_CLOSED_NOT_RUNTIME_ACTIVE";
    public bool CurrentGovernedStateGrantsRuntimeAuthority { get; init; } = false;
}

public static class FSAPMAManifest
{
    public static ApplicationManifest Current { get; } = new(
        "FSATS-FSAPMA", "Falcon.FSATS.FSAPMA", "0.1.0-part3", "FSATS Application Workstream",
        "Sole FSATS operational provider/data management Application.",
        "APPLICATION_DEVELOPMENT_GOVERNED_SOURCE", "EXACT_BUILD_ARTIFACT_IDENTITY_AND_DIGEST_REQUIRED_BEFORE_ADMISSION",
        "CONTRACT_VERSION_AND_FOUNDATION_BINDING_MUST_BE_EXPLICITLY_VERIFIED", "PART3_DURABILITY_IMPLEMENTATION_ONLY_NOT_RUNTIME_ACTIVE",
        "OPERATIONAL_PROVIDER_SELECTION_DATA_QUALITY_AND_DELIVERY_TRUTH_ONLY",
        "MSA-FSAPMA-01", Array.AsReadOnly(Enumerable.Range(1, 6).Select(i => $"P-LSA-{i:00}").ToArray()), Array.AsReadOnly(new[] { "CSA-P05-01" }),
        "CSA_ONLY_FOR_OWNER_ACCEPTED_ANOMALY_DETECTOR_WITH_PARENT_P_LSA_05",
        Array.AsReadOnly(new[] { "TRADING:GOVERNED_OPERATIONAL_DATA_CONSUMER", "TRADING_GUARDIAN:GOVERNED_EVIDENCE_AND_PROTECTION_STATUS", "APP-RSC:GOVERNED_RESOURCE_COORDINATION" }),
        Array.AsReadOnly(new[] { "ApplicationLifecycle", "Communication", "Evidence", "Resources", "Security", "CredentialReferenceResolution", "Persistence" }),
        Array.AsReadOnly(new[] { "APP-001", "CON-023", "FIL", "SERVICE_BUS", "SECURITY", "EVIDENCE", "CREDENTIAL_REFERENCE_RESOLUTION", "PERSISTENCE" }),
        Array.AsReadOnly(new[] { "PROVIDER_CONTROL", "PROVIDER_STREAM_CATALOG", "DATA_QUALITY_CLASSIFICATION", "OPERATIONAL_DATA_DELIVERY", "APPLICATION_DURABLE_RESTART_RECONSTRUCTION" }),
        Array.AsReadOnly(new[] { "AUTHORIZED_FSATS_OPERATIONAL_DATA_CONSUMERS_ONLY" }),
        Array.AsReadOnly(new[] { "APPLICATION_OWNED_PROVIDER_METADATA", "GOVERNED_CREDENTIAL_REFERENCES_ONLY", "GOVERNED_PERSISTENCE_PORT_ONLY", "NO_SECRET_BYTES_IN_MANIFEST_OR_LOGS" }),
        Array.AsReadOnly(new[] { "NO_PROVIDER_EGRESS_AUTHORITY_ACTIVE", "NO_RUNTIME_AUTHORITY_ACTIVE", "NO_PRODUCTION_PERSISTENCE_BINDING_AUTHORITY_ACTIVE" }),
        "DENY_UNDECLARED_PROVIDER_ROUTE_DESTINATION_SECRET_AND_AUTHORITY; PROVIDER_CREDENTIAL_REFERENCE_IS_NOT_BROKER_EXECUTION_CREDENTIAL; NO_CUSTOMER_OR_USER_IDENTITY_OWNERSHIP",
        "USE_ONLY_FOUNDATION_ADMITTED_ALLOCATION; DEGRADE_DATA_SERVICE_EXPLICITLY_UNDER_RESOURCE_PRESSURE; NO_FOUNDATION_RESOURCE_AUTHORITY",
        "APPLICATION_OWNED_PROVIDER_METADATA_DELIVERY_IDEMPOTENCY_AND_STREAM_CONTINUITY_STATE_HAVE_VERSIONED_DIGEST_BOUND_RECONSTRUCTION_SEMANTICS; CURRENT_STREAM_TRUTH_NEVER_SURVIVES_PROCESS_RESTART_WITHOUT_RECONCILIATION; GOVERNED_FOUNDATION_PERSISTENCE_BINDING_REQUIRED_FOR_RUNTIME; NO_LOCAL_PRODUCTION_SUBSTITUTE",
        "DECLARED_GOVERNED_ROUTES_ONLY; DELIVERY_OUTCOME_MUST_PRESERVE_ROUTE_AND_DATA_TRUTH; REPLAY_TEST_SIMULATION_NOT_OPERATIONAL",
        "GOVERNED_PROVIDER_API_AND_STREAM_CATALOG_QUOTA_AND_CONFIGURATION; REGISTERED_ENDPOINT_DOES_NOT_EQUAL_RUNTIME_AUTHORITY; MATERIAL_CHANGE_REQUIRES_REVIEW",
        "PROVIDER_OBSERVATION_PROVENANCE_QUALITY_DELIVERY_FAILURE_DURABILITY_AND_RECONSTRUCTION_EVIDENCE_ATTRIBUTABLE_AND_RECONSTRUCTABLE",
        "LIFECYCLE_STATES_DISTINCT; PART3_DOES_NOT_GRANT_ACTIVATION_OR_PROVIDER_CONNECTIVITY; RESTART_DOES_NOT_GRANT_STREAM_CONTINUITY",
        "REPORT_PROVIDER_QUALITY_ROUTE_READINESS_MSA_LSA_CSA_DEGRADED_AND_RECONSTRUCTION_STATE",
        "CONTAIN_PROVIDER_ROUTE_OR_PROVIDER_ACCOUNT_FAILURE_TO_PROVEN_SCOPE; UNKNOWN_BLAST_RADIUS_EXPANDS_CONTAINMENT; DO_NOT_POISON_UNAFFECTED_PROVIDER_ACCOUNTS_OR_BROKER_ACCOUNTS",
        "CSA_TO_PARENT_LSA_TO_MSA_TO_FSA_TO_SEPARATE_OWNER_GOVERNANCE; NO_CSA_RUNTIME_MUTATION_AUTHORITY",
        "TRADING_GUARDIAN_INTERACTION_REQUIRED_FOR_TRADING_SAFETY_INCIDENTS_BUT_FSAPMA_REMAINS_PROVIDER_TRUTH_OWNER",
        "GOVERNED_DATA_AND_INCIDENT_EVIDENCE_ROUTES; NO_DIRECT_PROTECTIVE_ACTION_AUTHORITY",
        "ROLLBACK_OR_APPROVED_CORRECTIVE_ACTION_PRESERVES_PROVIDER_STATE_PROVENANCE_EVIDENCE_ROUTE_TRUTH_DELIVERY_TOMBSTONES_AND_STREAM_RECONCILIATION; RECONNECTION_OR_RESTART_IS_NOT_RECOVERY",
        Array.AsReadOnly(new[] { "PROVIDER_SERVICE_CREDENTIAL_REFERENCE" }),
        RuntimeAuthorized: false, ProviderEgressAuthorized: false)
    {
        ResourceProfile = new(
            "SAFE_QUOTA_FRESHNESS_VALIDATION_RECONCILIATION_DURABLE_DELIVERY_FENCING_AND_CURRENT_PROVIDER_TRUTH_WITHIN_FOUNDATION_ADMITTED_ALLOCATION",
            "NORMAL_PROVIDER_SELECTION_ROUTING_QUALITY_AND_DELIVERY_CAPACITY_WITHIN_ADMITTED_ALLOCATION",
            "FOUNDATION_ADMITTED_CEILING_OR_USEFUL_BOUND_ONLY_NEVER_APPLICATION_MINTED",
            "PRESSURE_MUST_DEGRADE_OPTIONAL_PROVIDER_BREADTH_OR_FREQUENCY_EXPLICITLY_BEFORE_TRUTH_VALIDATION_RECONCILIATION_AND_IDEMPOTENCY_SAFETY",
            "NONESSENTIAL_PROVIDER_BREADTH_EXPERIMENTAL_SELECTION_AND_OPTIONAL_REFRESH_CAPACITY_IS_RECLAIMABLE",
            "SHED_OPTIONAL_BREADTH_AND_RATE; NEVER_EVICT_UNRESOLVED_DELIVERY_IDEMPOTENCY_OR_STREAM_RECONCILIATION_TRUTH",
            "RESTORE_ONLY_AFTER_FOUNDATION_ENVELOPE_PROVIDER_QUOTA_DATA_QUALITY_AND_REQUIRED_RECONSTRUCTED_CONTINUITY_STATE_ARE_REVALIDATED"),
        SafetyContinuityPolicy = "UNTRUSTED_SELECTION_AI_CANNOT_DISABLE_DETERMINISTIC_QUOTA_FRESHNESS_VALIDATION_RECONCILIATION_OR_PREAPPROVED_FAILOVER_OUTSIDE_THE_BLAST_RADIUS; RESTART_DEMOTES_UNPROVEN_CURRENT_STREAM_CONTINUITY_TO_RECONCILIATION_REQUIRED; UNKNOWN_BLAST_RADIUS_EXPANDS",
        AiRepairRecoveryPolicy = "DETECT->CONTAIN->INVESTIGATE->REPAIR_IN_ISOLATION->INDEPENDENT_VALIDATION->CONTROLLED_REVIVAL; R1_PREAUTHORIZED_NONSEMANTIC_ONLY; R2_OWNER_APPROVAL_BEFORE_REVIVAL; R3_OWNER_GOVERNANCE_MANDATORY",
        ReplacementRemovalPolicy = "RECONCILE_PROVIDER_IDENTITIES_ENTITLEMENTS_QUOTAS_CREDENTIAL_REFERENCES_ROUTES_PERSISTED_QUALITY_STATE_EVIDENCE_OPEN_DELIVERIES_DURABLE_IDEMPOTENCY_TOMBSTONES_STREAM_CONTINUITY_AND_DEPENDENCIES; NO_SIBLING_INHERITS_PROVIDER_AUTHORITY_BY_DEFAULT"
    };
}
