<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.FSAPMA.Application</AssemblyName><RootNamespace>Falcon.FSATS.FSAPMA.Application</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Contracts\Falcon.FSATS.FSAPMA.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Domain\Falcon.FSATS.FSAPMA.Domain.csproj" /></ItemGroup></Project>
