<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Falcon.FSATS.FoundationCompatibility.Verifier</AssemblyName>
    <RootNamespace>Falcon.FSATS.FoundationCompatibility.Verifier</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ResourceManagement\Falcon.FSATS.ResourceManagement.Application\Falcon.FSATS.ResourceManagement.Application.csproj" />
  </ItemGroup>
</Project>
