<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Falcon.FSATS.TradingGuardian.Host</AssemblyName><RootNamespace>Falcon.FSATS.TradingGuardian.Host</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Contracts\Falcon.FSATS.TradingGuardian.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Domain\Falcon.FSATS.TradingGuardian.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Application\Falcon.FSATS.TradingGuardian.Application.csproj" /><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Infrastructure\Falcon.FSATS.TradingGuardian.Infrastructure.csproj" /><ProjectReference Include="..\Falcon.FSATS.TradingGuardian.Awareness\Falcon.FSATS.TradingGuardian.Awareness.csproj" /></ItemGroup></Project>
