<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.ResourceManagement.Infrastructure</AssemblyName><RootNamespace>Falcon.FSATS.ResourceManagement.Infrastructure</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Contracts\Falcon.FSATS.ResourceManagement.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Domain\Falcon.FSATS.ResourceManagement.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Application\Falcon.FSATS.ResourceManagement.Application.csproj" /></ItemGroup></Project>
