<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Falcon.FSATS.ResourceManagement.Host</AssemblyName><RootNamespace>Falcon.FSATS.ResourceManagement.Host</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Contracts\Falcon.FSATS.ResourceManagement.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Domain\Falcon.FSATS.ResourceManagement.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Application\Falcon.FSATS.ResourceManagement.Application.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Infrastructure\Falcon.FSATS.ResourceManagement.Infrastructure.csproj" /><ProjectReference Include="..\Falcon.FSATS.ResourceManagement.Awareness\Falcon.FSATS.ResourceManagement.Awareness.csproj" /></ItemGroup></Project>
