<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>Foundation.MessageProtection</AssemblyName>
    <RootNamespace>Foundation.MessageProtection</RootNamespace>
  </PropertyGroup>
</Project>
