<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.FSTSimA.Infrastructure</AssemblyName><RootNamespace>Falcon.FSATS.FSTSimA.Infrastructure</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Contracts\Falcon.FSATS.FSTSimA.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Domain\Falcon.FSATS.FSTSimA.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSTSimA.Application\Falcon.FSATS.FSTSimA.Application.csproj" /></ItemGroup></Project>
