<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Falcon.FSATS.FSAPMA.Awareness</AssemblyName><RootNamespace>Falcon.FSATS.FSAPMA.Awareness</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Contracts\Falcon.FSATS.FSAPMA.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Domain\Falcon.FSATS.FSAPMA.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Application\Falcon.FSATS.FSAPMA.Application.csproj" /></ItemGroup></Project>
