<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Falcon.FSATS.FSAPMA.Host</AssemblyName><RootNamespace>Falcon.FSATS.FSAPMA.Host</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Contracts\Falcon.FSATS.FSAPMA.Contracts.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Domain\Falcon.FSATS.FSAPMA.Domain.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Application\Falcon.FSATS.FSAPMA.Application.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Infrastructure\Falcon.FSATS.FSAPMA.Infrastructure.csproj" /><ProjectReference Include="..\Falcon.FSATS.FSAPMA.Awareness\Falcon.FSATS.FSAPMA.Awareness.csproj" /></ItemGroup></Project>
